# Generated by Django 2.1.7 on 2019-03-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('long_url', models.URLField()),
                ('slug', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=32)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='url.Url')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
